### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ugintl** [robvanbakel/spark#1]
How to install it?

**Comment by robvanbakel** [comment]
Spark is a personal project, made to showcase Vue and Firebase skills in my portfolio. As I'm continuously changing the database layout and other structural components, I don't recommend installing Spark on your own.

If you do want to, clone the repo and install the dependencies. In `src/firebase/index.js`, replace the `firebaseConfig` with your app's Firebase project configuration and that should be it for the installation.

**Comment by ugintl** [comment]
@robvanbakel By "Install the dependencies" you mean running `npm install`?

**Comment by robvanbakel** [comment]
Yes! Clone or download the repo, run `npm install`, hook up your Firestore database and run `npm run serve` to start the application locally.
